import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import loadOtherFont from "next/font";
import NextLink from "next/link";
import { Link } from "@nextui-org/react";


{
  /* <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Hedvig+Letters+Serif:opsz@12..24&family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet">

</link> */
}
const nagoda = localFont({
  src: "../../public/fonts/Nagoda.otf",
  display: "auto",
});


export const metadata: Metadata = {
  title: "Wiredin Bible",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={nagoda.className}>
      <body>
        <main className="min-h-screen flex flex-col">
          <div className="py-20 max-w-5xl mx-auto">
            <div className="text-center">
              <NextLink href="/" className="text-2xl tracking-widest font-bold">
                THE WIRED BIBLE
              </NextLink>
            </div>
            <div className="pt-20">{children}</div>
          </div>
          <footer className="text-center text-sm py-3 mt-auto">
            XO, From{" "}
            <Link color="warning" href="https://github.com/Nie-Mand">
              @Nie-Mand
            </Link>
          </footer>
        </main>
      </body>
    </html>
  );
}
