import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Link from "next/link";

const nagoda = localFont({
  src: "../../public/fonts/Nagoda.otf",
  display: "auto",
});

export const metadata: Metadata = {
  title: "Wired Bible",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={nagoda.className}>
      <body>
        <main className="min-h-screen py-20">
          <div className="max-w-5xl mx-auto">
            <div className="text-center">
              <Link href="/" className="text-2xl tracking-widest font-bold">
                THE WIRED BIBLE
              </Link>
            </div>
            <div className="pt-20">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
